/**
 * Nội dung landing trùng với AG/lang/vi/landingpage.php (+ public.php cho nhãn khóa học)
 * và cấu trúc AG/resources/views/web/default/pages/homev2.blade.php
 */
export const AG_LANDING_VI = {
  /** Hero đầu trang (tagline nền tảng — đồng bộ messaging web cũ Glocal IELTS) */
  hero_platform_title: "Nền tảng thi IELTS lớn nhất Việt Nam",
  practice_test: "Thi thử ",
  receive_detailed_editing_results: "NHẬN KẾT QUẢ CHẤM SỬA CHI TIẾT",
  student_joined: "học sinh đã tham gia",
  register_now: "Đăng ký ngay",
  listening: "nghe",
  speaking: "nói",
  reading: "đọc",
  writing: "viết",
  support: "Hỗ trợ",
  for_ielts_exam_registration: "đăng ký thi IELTS",
  with_idp_or_british_council: "CÙNG IDP HOẶC BRISTISH COUNCIL",
  convenient: "TIỆN",
  expense: "TIỀN",
  tam: "TÂM",
  conten01:
    "Chỉ cần gửi thông tin, mọi thủ tục sẽ được hỗ trợ từ A đến Z (Điền đơn đăng ký, đặt lịch, nhận-trả kết quả tận nhà ...)",
  conten02:
    "Tối ưu chi phí với các trải nghiệm học và thi vui, hiệu quả với các chương trình và gói hỗ trợ độc quyền, tiết kiệm",
  conten03:
    "Được cung cấp tài liệu ôn thi, hỗ trợ thi thử, tạo nhóm học tập, nhắc nhở lịch thi, cố vấn phát triển trọn đời trước và sau",
  events: "SỰ KIỆN",
  upcoming: "SẮP DIỄN RA",
  courses: "CÁC KHOÁ DẠY VÀ HỌC IELTS",
  courses_attribute: "VUI - HIỆU QUẢ - TIẾT KIỆM",
  public_objective: "Đối tượng",
  public_duration: "Thời lượng",
  public_achievement: "Chứng chỉ",
  public_free: "Miễn phí",
  buynow: "Mua ngay",
  text1: "CHƯƠNG TRÌNH CỐ ",
  text2: "VẤN LÀ GÌ?",
  conten04: "Không dạy lý thuyết, tập trung THỰC HÀNH - SỬA LỖI - MỞ RỘNG - HỆ THỐNG KIẾN THỨC",
  conten05: "Có khung chương trình, hoạt động, nội dung khoa học, chặt chẽ giữa GV và HV",
  conten06: "Bám sát năng lực ngôn ngữ: TƯ DUY - PHẢN XẠ - TIẾP THU THỤ ĐỘNG",
  content14: "Thực hành IELTS với giáo viên Lớp 1:1 hoặc nhóm nhỏ 3-5 HV",
  content15: "Bám sát năng lực và vấn đề ngôn ngữ của học viên",
  content16: "Tối đa thực hành và bức phá năng lực thật",
  content17: "Được theo dõi chặt chẽ và đánh giá chất lượng trên từng buổi học",
  more: "Tìm hiểu thêm",
  content19: "Giao lưu văn hoá với giáo viên bản xứ Canada",
  content20: "Chương trình thiết kế độc quyền",
  content21: "Thực hành tiếng Anh thực tế trước khi đi du học, định cư",
  content22: "Làm quen văn hoá Canada với mentor địa phương",
  other: "khác",
  passion_for_lifetime_companion: "đam mê đồng hành trọn đời",
  tab_study_abroad_consulting: "Chương trình ngoại khoá",
  tab_study_abroad_support: "Tư vấn du học",
  tab_doVisa: "Làm Visa",
  content26: "Trải nghiệm - thử thách- thực hành- thay đổi tích cực",
  content27: "Cố vấn chọn chương trình phù hợp với nhu cầu, năng lực PH, HS",
  content28: "Đồng hành học tập, phát triển bản thân trọn đời",
  content08: "Cố vấn chuyên gia theo văn hoá, chuyên ngành, định hướng học, làm hoặc định cư phù hợp với mong muốn",
  content09: "Đồng hành trọn đời",
  content10: "Bảo hành mọi vấn đề",
  understand_visa_law: "Hiểu rõ Luật Visa",
  well_groomed_and_professional: "Chỉnh chu, chuyên nghiệp",
  canada_usa_australia_new_zealand: "Canada, USA, Australia, New Zealand",
  register_support_now: "ĐĂNG KÝ HỖ TRỢ NGAY",
  what_for_support: "Nhu cầu bạn cần hổ trợ là gì?",
  choose_your_need: "Chọn nhu cầu",
  opt_ietls_practice_test: "Thi thử IELTS",
  opt_support_registration: "Hỗ trợ đăng ký thi IELTS",
  opt_video_english_course: "Khoá học tiếng Anh thông qua video",
  opt_mentorship: "Cố vấn - mentorship",
  opt_ielts_class: "Tư vấn lớp IELTS 1-1 hoặc 3-5",
  opt_classes_with_native: "Tư vấn lớp giao lưu văn hoá với giáo viên người bản xứ Canada",
  opt_visa: "Tư vấn Visa",
  opt_study_abroad: "Tư vấn du học",
  opt_register_extracurricular_program: "Đăng ký chương trình ngoại khoá",
  full_name: "Họ và Tên",
  printed_in_capitals_and_accented: "*in hoa và có dấu",
  phone: "Số điện thoại",
  email: "Email",
  code_refer: "Mã giới thiệu",
  register: "Đăng ký tư vấn",
  story: "CÂU CHUYỆN",
  from_ielts_to_local_impact: "“FROM IELTS TO LOCAL IMPACT”",
  vision: "Tầm nhìn",
  content11: "Nền tảng học, dạy, thực hành và kết nối IELTS hiệu quả toàn cầu",
  mission: "Sứ mệnh",
  content12:
    "Từ học IELTS đến phát triển thành công dân toàn cầu, người có suy nghĩ toàn cầu và hành động địa phương",
  content23: "“TỪ 2 LẦN ĐẠT TOP CHUNG KẾT CUỘC THI SÁNG TẠO DOANH",
  content24: "NGHIỆP XÃ HỘI 2022 VÀ KHAO KHÁT RA THẾ GIỚI VÀ PHÁT",
  content25: "TRIỂN TẠI CANADA”",
  feeling: "CẢM NHẬN",
  client: "KHÁCH HÀNG",
  partner: "Đối tác",
  register_success: "Cảm ơn bạn đã đăng ký, chúng tôi sẽ liên hệ sớm nhất với bạn",
} as const;
